# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4368fed47b3882e9a8e22d649a2da05b03677c5852b0e0d01b216304afbd6e8bce3723ae0b91b6b01fcfaea890ad268808121350c4e090d269d0db5caba2da93

test:
  secret_key_base: b5c737a71271bcd8b469eb2f87853bd52a102f6ca2de8d4405fc698e4de477d6d808cf23ae766e60478cc813369a013187f85e3fac8c80965758474b6a1fbf89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
